name: Deploy Documentation

# Trigger the workflow on push to the default branch or when manually triggered
on:
  push:
    branches:
      - main  # Replace with your default branch if different
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme  # Add any other Sphinx extensions you use

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}